# Generated by Django 3.1.5 on 2021-01-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('zip', models.CharField(default='', max_length=200)),
                ('email', models.CharField(default='email', max_length=100)),
                ('name', models.CharField(default='name', max_length=100)),
                ('description', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
