# Generated by Django 3.1.5 on 2021-01-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0006_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(default='../media/default-img.gif', upload_to=''),
        ),
    ]
