# Generated by Django 3.1.5 on 2021-01-21 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0018_auto_20210121_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('success', 'New'), ('primary', 'Like New'), ('secondary', 'Fair'), ('warning', 'Acceptable'), ('danger', 'Poor')], default='secondary', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 2, 40, 59, 356284)),
        ),
    ]
