# Generated by Django 3.1.5 on 2021-01-21 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0019_auto_20210121_0240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('LIKE NEW', 'Like New'), ('FAIR', 'Fair'), ('ACCEPTABLE', 'Acceptable'), ('POOR', 'Poor')], default='secondary', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 2, 57, 57, 476134)),
        ),
    ]
