# Generated by Django 3.1.5 on 2021-01-21 02:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0021_auto_20210121_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 2, 58, 27, 125080)),
        ),
    ]
