# Generated by Django 3.1.5 on 2021-01-28 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0023_auto_20210124_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('HOME_APPLIANCES', 'Home Appliances'), ('SMARTPHONES', 'Smart Phones'), ('LAPTOPS', 'Laptops'), ('TABLETS', 'Tablets'), ('BOOKS', 'Books'), ('SPORTS/OUTDOOR', 'Sports and Outdoor'), ('CLOTHING', 'Clothing'), ('FURNITURE', 'Furniture'), ('OTHER', 'Other'), ('', 'Please select a category')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 28, 3, 57, 16, 515356)),
        ),
    ]
