# Generated by Django 3.1.5 on 2021-01-28 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0024_auto_20210128_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='condition',
            field=models.CharField(choices=[('NEW', 'New'), ('LIKE NEW', 'Like New'), ('FAIR', 'Fair'), ('ACCEPTABLE', 'Acceptable'), ('POOR', 'Poor'), ('', 'Select the condition')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 28, 3, 59, 2, 466075)),
        ),
    ]
