# Generated by Django 3.1.5 on 2021-01-28 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0025_auto_20210128_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('HOME_APPLIANCES', 'Home Appliances'), ('SMARTPHONES', 'Smart Phones'), ('LAPTOPS', 'Laptops'), ('TABLETS', 'Tablets'), ('BOOKS', 'Books'), ('SPORTS/OUTDOOR', 'Sports and Outdoor'), ('CLOTHING', 'Clothing'), ('FURNITURE', 'Furniture'), ('OTHER', 'Other'), ('', 'Select a category')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='datePosted',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 28, 4, 12, 29, 190584)),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
